### ISSUE TITLE
The scenario_damage and scenario_risk do not run with a single configuration file

### ISSUE THREAD

**Issue by micheles** [gem/oq-risklib#473]
Currently instead there is an error if one merges the hazard and risk files:

```python
CRITICAL:root:
Traceback (most recent call last):
  File "/usr/local/openquake/oq-risklib/openquake/calculators/base.py", line 114, in run
    self.pre_execute()
  File "/usr/local/openquake/oq-risklib/openquake/calculators/scenario.py", line 66, in pre_execute
    super(ScenarioCalculator, self).pre_execute()
  File "/usr/local/openquake/oq-risklib/openquake/calculators/base.py", line 274, in pre_execute
    self.read_exposure_sitecol()
  File "/usr/local/openquake/oq-risklib/openquake/calculators/base.py", line 289, in read_exposure_sitecol
    self.gmfs = get_gmfs(self)
  File "/usr/local/openquake/oq-risklib/openquake/calculators/base.py", line 489, in get_gmfs
    gmf = calc.datastore['gmfs/col00'].value
  File "/usr/local/openquake/oq-risklib/openquake/commonlib/datastore.py", line 273, in __getitem__
    raise KeyError('No %r found in %s' % (key, self))
KeyError: "No 'gmfs/col00' found in <DataStore 2>"
```

**Comment by micheles** [comment]
Duplicate of https://github.com/gem/oq-risklib/issues/473
