### ISSUE TITLE
oq-lite show command not working on non-utf8 terminals

### ISSUE THREAD

**Issue by daniviga** [gem/oq-risklib#737]
On non UTF-8 terminals (like the Windows command interface) the `oq-lite show`  command does not work if the job contains UTF-8 chars. The error is:

```python
Traceback (most recent call last):
  File "C:\Program Files (x86)\OpenQuake Engine Lite\oq-lite.py", line 32, in <module>
    oq_lite()
  File "C:\Program Files (x86)\OpenQuake Engine Lite\pkgs\openquake\commonlib\commands\__main__.py", line 33, in oq_lite
    parser.callfunc()
  File "C:\Program Files (x86)\OpenQuake Engine Lite\pkgs\openquake\commonlib\sap.py", line 170, in callfunc
    return self.func(**vars(namespace))
  File "C:\Program Files (x86)\OpenQuake Engine Lite\pkgs\openquake\commonlib\sap.py", line 204, in main
    return func(**kw)
  File "C:\Program Files (x86)\OpenQuake Engine Lite\pkgs\openquake\commonlib\commands\show.py", line 99, in show
    print(datastore.view(what, ds))
  File "C:\Program Files (x86)\Common Files\Python\2.7\lib\encodings\cp850.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2014' in position 53: character maps to <undefined>
```

Adding `.encode('utf-8')` to https://github.com/gem/oq-risklib/blob/master/openquake/commonlib/commands/show.py#L99 seems to fix the issue.

**Comment by micheles** [comment]
The show command has changed. We must check if the error is already there.

**Comment by daniviga** [comment]
Still not perfect, but at least it works!

```
C:\Programmi\OpenQuake Engine>oq-lite.py show all
#1 classical: Classical PSHA ÔÇö Area Source
```

**Comment by micheles** [comment]
I would consider this as closed, at least for the time being. Inferring the encoding of the terminal across different platforms (and considering also non tty outputs) looks like a lot of effort for a minimal benefit.
